"""Detection signals.

Signal 1 (Groq LLM) and Signal 2 (stylometric heuristics, pure Python). The
fusion logic lives in scoring.py. See planning.md §2 and §5.1.
"""
import json
import os
import re
import statistics

from dotenv import load_dotenv
from groq import Groq

load_dotenv()

MODEL = "llama-3.3-70b-versatile"

# Map the LLM's qualitative self-confidence to a numeric fusion weight (§5.1).
_CONFIDENCE_WEIGHTS = {"high": 1.0, "medium": 0.6, "low": 0.3}

_SYSTEM_PROMPT = (
    "You are an AI-text detector for a writing platform. You will be given a piece "
    "of text. Judge how likely it is to have been generated by an AI writing tool "
    "(e.g. ChatGPT) rather than written by a human.\n\n"
    "Consider distributional cues: AI text tends to be smooth, evenly toned, "
    "low-surprise, and full of safe, generic phrasing and predictable transitions. "
    "Human text tends to be more idiosyncratic, specific, and uneven.\n\n"
    "Respond with ONLY a JSON object of the form:\n"
    '{"score": <float 0-1>, "confidence": "high"|"medium"|"low", '
    '"rationale": "<one short sentence>"}\n'
    "score = probability the text is AI-generated (0.0 = certainly human, "
    "1.0 = certainly AI). confidence = how sure you are of that score."
)

_client = None


def _get_client():
    """Lazily construct the Groq client so import never fails on a missing key."""
    global _client
    if _client is None:
        api_key = os.environ.get("GROQ_API_KEY")
        if not api_key:
            raise RuntimeError("GROQ_API_KEY is not set (check your .env file).")
        _client = Groq(api_key=api_key)
    return _client


def _clamp01(x):
    return max(0.0, min(1.0, float(x)))


def detect_llm(text):
    """Signal 1 — ask the Groq LLM how likely `text` is AI-generated.

    Returns a dict matching planning.md §5.1:
        {
            "score":      float in [0, 1]   # likelihood AI (1.0 = certainly AI)
            "weight":     float in [0, 1]    # self-confidence as a fusion weight
            "confidence": "high"|"medium"|"low",
            "rationale":  str,
        }

    Raises on transport/API failure so the caller can decide on degraded mode
    (§5.3) — this function does not swallow errors.
    """
    client = _get_client()
    completion = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
        temperature=0.0,  # deterministic-ish: we want a stable judgement
        response_format={"type": "json_object"},
    )
    raw = completion.choices[0].message.content
    data = json.loads(raw)

    score = _clamp01(data.get("score", 0.5))
    confidence = str(data.get("confidence", "medium")).lower()
    if confidence not in _CONFIDENCE_WEIGHTS:
        confidence = "medium"
    rationale = str(data.get("rationale", "")).strip()

    return {
        "score": round(score, 4),
        "weight": _CONFIDENCE_WEIGHTS[confidence],
        "confidence": confidence,
        "rationale": rationale,
    }


# --------------------------------------------------------------------------- #
# Signal 2 — Stylometric heuristics (pure Python, no external service). §2, §5.1
# --------------------------------------------------------------------------- #

# Connective / transition phrases that AI text leans on heavily (§2 Signal 1
# blind spot is the LLM's; here stylometry catches the *structural* tell).
_TRANSITIONS = [
    "furthermore", "moreover", "however", "additionally", "consequently",
    "therefore", "thus", "nevertheless", "nonetheless", "in conclusion",
    "in summary", "it is important to note", "it is worth noting",
    "it is essential", "on the other hand", "as a result", "in today's",
    "play a crucial role", "play a vital role", "a wide range of",
]

# Informal markers that point toward casual human writing.
_CASUAL_WORDS = {
    "ok", "okay", "honestly", "lol", "yeah", "yep", "nope", "gonna", "wanna",
    "kinda", "sorta", "stuff", "anyway", "basically", "literally", "ugh", "meh",
}

# Length → self-confidence weight (§5.1): stylometry is unreliable on short text.
def _length_weight(word_count):
    if word_count < 50:
        return 0.3
    if word_count <= 200:
        return 0.6
    return 1.0


def detect_stylometry(text):
    """Signal 2 — surface-statistics estimate of how AI-like `text` is.

    Returns the §5.1 shape: {score, weight, confidence, metrics}. score is a
    0-1 "looks-AI" value (1.0 = very AI-like). Deterministic; no network.
    """
    words = re.findall(r"[A-Za-z']+", text.lower())
    word_count = len(words)
    sentences = [s for s in re.split(r"[.!?]+", text) if s.strip()]
    sent_lengths = [len(re.findall(r"[A-Za-z']+", s)) for s in sentences] or [word_count]

    mean_len = statistics.mean(sent_lengths)
    std_len = statistics.pstdev(sent_lengths) if len(sent_lengths) > 1 else 0.0
    cv = (std_len / mean_len) if mean_len else 0.0  # coefficient of variation

    ttr = len(set(words)) / word_count if word_count else 0.0

    lowered = text.lower()
    transition_hits = sum(lowered.count(t) for t in _TRANSITIONS)
    transition_density = transition_hits / max(len(sentences), 1)

    contractions = len(re.findall(r"\b\w+'\w+\b", lowered))
    casual_hits = sum(1 for w in words if w in _CASUAL_WORDS)
    lowercase_starts = sum(1 for s in sentences if s.strip()[:1].islower())
    casual_count = contractions + casual_hits + lowercase_starts

    def clamp(x):
        return max(0.0, min(1.0, x))

    # Per-metric "AI-ness" sub-scores in [0, 1].
    burstiness_ai = 1.0 - clamp(cv / 0.65)          # low variance  -> AI
    length_ai = clamp((mean_len - 11) / 14.0)       # long, uniform -> AI
    transition_ai = clamp(transition_density / 0.4)  # heavy connectives -> AI
    lexical_ai = clamp((0.72 - ttr) / 0.40)          # low diversity -> AI-ish

    base = (
        0.35 * burstiness_ai
        + 0.25 * length_ai
        + 0.30 * transition_ai
        + 0.10 * lexical_ai
    )
    # Casual/informal writing is a strong human tell — damp the score down.
    casual_factor = clamp(casual_count / 4.0)
    score = clamp(base * (1.0 - 0.45 * casual_factor))

    weight = _length_weight(word_count)
    confidence = {1.0: "high", 0.6: "medium", 0.3: "low"}[weight]

    return {
        "score": round(score, 4),
        "weight": weight,
        "confidence": confidence,
        "metrics": {
            "word_count": word_count,
            "sentences": len(sentences),
            "mean_sentence_len": round(mean_len, 2),
            "burstiness_cv": round(cv, 3),
            "type_token_ratio": round(ttr, 3),
            "transition_density": round(transition_density, 3),
            "casual_markers": casual_count,
        },
    }


if __name__ == "__main__":
    # Direct test harness — run BEFORE wiring into the endpoint:
    #     python detection.py
    samples = {
        "obvious AI (generic blog intro)": (
            "In today's fast-paced digital world, it is more important than ever to "
            "leverage cutting-edge solutions. By embracing innovation and fostering "
            "collaboration, organizations can unlock their full potential and drive "
            "sustainable growth across every facet of the business."
        ),
        "human (specific, uneven)": (
            "My grandmother kept her teeth in a jam jar by the sink. I hated that jar. "
            "Now she's gone and I'd give anything to be grossed out by it one more time."
        ),
        "short/ambiguous": "The sun dipped below the horizon and the porch went quiet.",
    }
    for name, sample in samples.items():
        print(f"\n[{name}]")
        print("  llm       :", json.dumps(detect_llm(sample)))
        print("  stylometry:", json.dumps(detect_stylometry(sample)))
